name: mvp_flutter
description: "A framework that easily implements the MVP(Model-View-Presenter) architecture in Flutter"
version: 0.0.2
homepage: "https://github.com/xaatw0/flutter_salon_packages/mvp"

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:

