name: ollama_talk_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  objectbox: ^4.0.1
  ollama_talk_common:
    path: ../ollama_talk_common

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.12
  objectbox_generator: any
