name: ollama_talk_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  build_runner: ^2.4.11
  dart_frog: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  objectbox: ^4.0.1
  ollama_talk_common:
    path: ../ollama_talk_common
  web_socket_channel: ^2.4.5

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  objectbox_generator: any
  mockito: ^5.4.4
